# Generated by Django 5.1.1 on 2024-09-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_tasks_note_tasks_priority_user_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='parkingAvaliable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='property_features',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='wifiAvaliabe',
            field=models.BooleanField(default=False),
        ),
    ]
