# Generated by Django 5.1.1 on 2024-10-06 06:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0004_project_parkingavaliable_project_property_features_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPalPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('response', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_pay', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pay_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
