# Generated by Django 5.1.1 on 2024-10-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0005_paypalpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paypalpayment',
            name='status',
            field=models.CharField(blank=True, default='created', max_length=200, null=True),
        ),
    ]
