# Generated by Django 5.1.1 on 2024-10-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0006_alter_paypalpayment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypalpayment',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
