# Generated by Django 5.1.1 on 2024-10-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0007_paypalpayment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypalpayment',
            name='PayementId',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
