# Generated by Django 5.1.1 on 2024-10-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0008_paypalpayment_payementid'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypalpayment',
            name='type',
            field=models.CharField(default='paypal', max_length=200),
        ),
    ]
