# Generated by Django 5.1.1 on 2024-10-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0012_alter_paypalpayment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypalpayment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
