# Generated by Django 5.1.1 on 2024-10-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0014_alter_paypalpayment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paypalpayment',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
