# Generated by Django 5.1.1 on 2024-10-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0015_alter_paypalpayment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypalpayment',
            name='enableTax',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paypalpayment',
            name='itemsList',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
