# Generated by Django 5.1.1 on 2024-09-28 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_auto_20240520_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='note',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worker_supplier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Mananger'), ('contractor', 'Contractor'), ('client', 'Client'), ('worker', 'Worker'), ('supplier', 'Supplier')], default='admin', max_length=200),
        ),
    ]
