# Generated by Django 5.1.1 on 2024-10-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0009_paypalpayment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paypalpayment',
            name='type',
            field=models.CharField(default='PayPal', max_length=200),
        ),
    ]
