# Generated by Django 5.1.1 on 2024-10-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0010_alter_paypalpayment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypalpayment',
            name='checkoutLink',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
