# Generated by Django 5.1.1 on 2024-10-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0013_paypalpayment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paypalpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
